filter:
    paths:
        - src/main/java/
build:
    environment:
        java: 'java-8-oracle'
    nodes:
        analysis:
            environment:
                docker:
                    remote_engine: true
            tests:
                override:
                    - java-scrutinizer-run
        coverage:
          tests:
            override:
              - command: mvn clean verify -Pqulice,jacoco --errors --batch-mode
                coverage:
                  file: 'target/site/jacoco/jacoco.xml'
                  format: 'jacoco'
checks:
    java:
        code_rating: true