language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: required
cache:
  directories:
    - $HOME/.m2
script:
  - ./.travis/run.sh
install:
  - sudo apt-get update
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "paulodamaso-github"
    token:
      secure: d5d0d4d4908def3bcc19deb8dbae14317dfbf15a
#  script:
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar